[script://./bin/usb_monitor.py]
disabled = 0
interval = 60
source = usb_monitor
sourcetype = usb:activity
index = usb_security

[script://./bin/usb_monitor.py --mode service]
disabled = 0
interval = 30
source = usb_monitor_service
sourcetype = usb:events
index = usb_security

[monitor:///tmp/usb_monitor_data/usb_events.json]
disabled = 0
sourcetype = usb:events
index = usb_security
followTail = 1

[monitor:///tmp/usb_monitor_data/splunk_export.json]
disabled = 0
sourcetype = usb:activity
index = usb_security
followTail = 1

[monitor:///tmp/usb_monitor_data/usb_activity_sample.csv]
disabled = 0
sourcetype = usb:activity
index = usb_security
followTail = 1